// 多语言支持文件
const languages = {
    'zh-CN': { // 简体中文
        title: '灵验咒符查询系统',
        subtitle: '探寻天机，解析命运，消灾纳福，趋吉避凶',
        birthYear: '阴历出生年份',
        birthMonth: '阴历出生月份',
        birthTime: '出生时辰',
        pleaseSelect: '请选择',
        month1: '正月',
        month2: '二月',
        month3: '三月',
        month4: '四月',
        month5: '五月',
        month6: '六月',
        month7: '七月',
        month8: '八月',
        month9: '九月',
        month10: '十月',
        month11: '十一月',
        month12: '十二月',
        hour1: '子时 (23:00-01:00)',
        hour2: '丑时 (01:00-03:00)',
        hour3: '寅时 (03:00-05:00)',
        hour4: '卯时 (05:00-07:00)',
        hour5: '辰时 (07:00-09:00)',
        hour6: '巳时 (09:00-11:00)',
        hour7: '午时 (11:00-13:00)',
        hour8: '未时 (13:00-15:00)',
        hour9: '申时 (15:00-17:00)',
        hour10: '酉时 (17:00-19:00)',
        hour11: '戌时 (19:00-21:00)',
        hour12: '亥时 (21:00-23:00)',
        queryBtn: '灵符查询',
        resultTitle: '灵符命理分析结果',
        bengMing: '本命宫位',
        suiJun: '岁君',
        fortune: '吉凶',
        lingFu: '灵符',
        effect: '效用',
        usageMethod: '灵符使用方法',
        usageSteps: [
            '在佛堂或者干净的地方，于太阳出后至中午 13:00 之间进行，个别符咒使用非此时段。',
            '折角：南无大慈悲父！（三遍）',
            '请灵验咒符的神灵、天人、护法神降临！（三遍）',
            '摆供：红、香、花、果、茶、糕饼等，随方便进行供养，本门子孙皆可供养。',
            '祈请师父、本命、护法降临！（遍）',
            '祈请灵验咒符的神灵、天人、护法护佑！（三遍）',
            '把自己所要变的解除灾难的事情说明，请求加持和护佑。',
            '念念子大明咒 21 遍以上，回向灵验咒符的神灵、天人、护法神，感恩他们。',
            '将祈祷等花化，或化香，或焚纸于火，具体请参考灵符卷内的谕示文字。'
        ],
        footer: '灵验咒符查询系统 © 2025 | 趋吉避凶，消灾纳福',
        inputValidation: '请完整填写阴历出生年月和时辰信息！',
        inputSummary: '阴历出生：{birthYear}年（{birthZodiac}年）{birthMonth}{birthTime}时 | 当前年份：{currentYear}年（{currentYearZodiac}年）',
        yearFormat: '{year}年 ({zodiac}年)',
        languageName: '简体中文'
    },
    'zh-TW': { // 繁体中文
        title: '靈驗咒符查詢系統',
        subtitle: '探尋天機，解析命運，消災納福，趨吉避凶',
        birthYear: '陰曆出生年份',
        birthMonth: '陰曆出生月份',
        birthTime: '出生時辰',
        pleaseSelect: '請選擇',
        month1: '正月',
        month2: '二月',
        month3: '三月',
        month4: '四月',
        month5: '五月',
        month6: '六月',
        month7: '七月',
        month8: '八月',
        month9: '九月',
        month10: '十月',
        month11: '十一月',
        month12: '十二月',
        hour1: '子時 (23:00-01:00)',
        hour2: '丑時 (01:00-03:00)',
        hour3: '寅時 (03:00-05:00)',
        hour4: '卯時 (05:00-07:00)',
        hour5: '辰時 (07:00-09:00)',
        hour6: '巳時 (09:00-11:00)',
        hour7: '午時 (11:00-13:00)',
        hour8: '未時 (13:00-15:00)',
        hour9: '申時 (15:00-17:00)',
        hour10: '酉時 (17:00-19:00)',
        hour11: '戌時 (19:00-21:00)',
        hour12: '亥時 (21:00-23:00)',
        queryBtn: '靈符查詢',
        resultTitle: '靈符命理分析結果',
        bengMing: '本命宮位',
        suiJun: '歲君',
        fortune: '吉凶',
        lingFu: '靈符',
        effect: '效用',
        usageMethod: '靈符使用方法',
        usageSteps: [
            '在佛堂或者乾淨的地方，於太陽出後至中午 13:00 之間進行，個別符咒使用非此時段。',
            '折角：南無大慈悲父！（三遍）',
            '請靈驗咒符的神靈、天人、護法神降臨！（三遍）',
            '擺供：紅、香、花、果、茶、糕餅等，隨方便進行供養，本門子孫皆可供養。',
            '祈請師父、本命、護法降臨！（遍）',
            '祈請靈驗咒符的神靈、天人、護法護佑！（三遍）',
            '把自己所要變的解除災難的事情說明，請求加持和護佑。',
            '念念子大明咒 21 遍以上，回向靈驗咒符的神靈、天人、護法神，感恩他們。',
            '將祈禱等花化，或化香，或焚紙於火，具體請參考靈符卷內的諭示文字。'
        ],
        footer: '靈驗咒符查詢系統 © 2025 | 趨吉避凶，消災納福',
        inputValidation: '請完整填寫陰曆出生年月和時辰信息！',
        inputSummary: '陰曆出生：{birthYear}年（{birthZodiac}年）{birthMonth}{birthTime}時 | 當前年份：{currentYear}年（{currentYearZodiac}年）',
        yearFormat: '{year}年 ({zodiac}年)',
        languageName: '繁體中文'
    },
    'en': { // 英文
        title: 'Spiritual Talisman Query System',
        subtitle: 'Explore destiny, analyze fate, dispel disasters, and attract good fortune',
        birthYear: 'Lunar Birth Year',
        birthMonth: 'Lunar Birth Month',
        birthTime: 'Birth Hour',
        pleaseSelect: 'Please Select',
        month1: '1st Month',
        month2: '2nd Month',
        month3: '3rd Month',
        month4: '4th Month',
        month5: '5th Month',
        month6: '6th Month',
        month7: '7th Month',
        month8: '8th Month',
        month9: '9th Month',
        month10: '10th Month',
        month11: '11th Month',
        month12: '12th Month',
        hour1: 'Zi (23:00-01:00)',
        hour2: 'Chou (01:00-03:00)',
        hour3: 'Yin (03:00-05:00)',
        hour4: 'Mao (05:00-07:00)',
        hour5: 'Chen (07:00-09:00)',
        hour6: 'Si (09:00-11:00)',
        hour7: 'Wu (11:00-13:00)',
        hour8: 'Wei (13:00-15:00)',
        hour9: 'Shen (15:00-17:00)',
        hour10: 'You (17:00-19:00)',
        hour11: 'Xu (19:00-21:00)',
        hour12: 'Hai (21:00-23:00)',
        queryBtn: 'Query Talisman',
        resultTitle: 'Talisman Analysis Results',
        bengMing: 'Life Palace Position',
        suiJun: 'Year Lord',
        fortune: 'Fortune',
        lingFu: 'Talisman',
        effect: 'Effects',
        usageMethod: 'Talisman Usage Method',
        usageSteps: [
            'Perform in a clean place or Buddhist altar between sunrise and 13:00, with some specific talismans requiring different timing.',
            'Fold the corner and recite: "Homage to the Great Compassionate Father!" (three times)',
            'Invite the deities, celestial beings, and guardian spirits of the efficacious talisman to descend! (three times)',
            'Arrange offerings: red items, incense, flowers, fruits, tea, cakes, etc., as convenient. All disciples can make offerings.',
            'Invite the master, life guardian, and protectors to descend! (once)',
            'Pray for the protection of the deities, celestial beings, and guardian spirits of the efficacious talisman! (three times)',
            'Explain the disaster or difficulty you wish to resolve and request blessings and protection.',
            'Recite the Great Brightness Mantra 21 times or more, dedicating the merit to the deities, celestial beings, and guardian spirits of the efficacious talisman, expressing gratitude to them.',
            'Burn the prayer offerings, incense, or paper in fire, following the specific instructions in the talisman scroll.'
        ],
        footer: 'Spiritual Talisman Query System © 2025 | Avoid disasters and attract good fortune',
        inputValidation: 'Please complete all lunar birth year, month, and hour information!',
        inputSummary: 'Lunar Birth: {birthYear} ({birthZodiac}) {birthMonth} {birthTime} | Current Year: {currentYear} ({currentYearZodiac})',
        yearFormat: '{year} ({zodiac})',
        languageName: 'English'
    },
    'ja': { // 日文
        title: '霊験お札検索システム',
        subtitle: '天機を探り、運命を解析し、災いを消し、福を招き、吉を求め凶を避ける',
        birthYear: '旧暦生年',
        birthMonth: '旧暦生月',
        birthTime: '生まれ時刻',
        pleaseSelect: '選択してください',
        month1: '正月',
        month2: '二月',
        month3: '三月',
        month4: '四月',
        month5: '五月',
        month6: '六月',
        month7: '七月',
        month8: '八月',
        month9: '九月',
        month10: '十月',
        month11: '十一月',
        month12: '十二月',
        hour1: '子の刻 (23:00-01:00)',
        hour2: '丑の刻 (01:00-03:00)',
        hour3: '寅の刻 (03:00-05:00)',
        hour4: '卯の刻 (05:00-07:00)',
        hour5: '辰の刻 (07:00-09:00)',
        hour6: '巳の刻 (09:00-11:00)',
        hour7: '午の刻 (11:00-13:00)',
        hour8: '未の刻 (13:00-15:00)',
        hour9: '申の刻 (15:00-17:00)',
        hour10: '酉の刻 (17:00-19:00)',
        hour11: '戌の刻 (19:00-21:00)',
        hour12: '亥の刻 (21:00-23:00)',
        queryBtn: 'お札を検索',
        resultTitle: 'お札命理分析結果',
        bengMing: '本命宮位',
        suiJun: '歳君',
        fortune: '吉凶',
        lingFu: 'お札',
        effect: '効用',
        usageMethod: 'お札使用方法',
        usageSteps: [
            '仏壇または清潔な場所で、太陽が出てから正午13:00までの間に行う。一部のお札は異なる時間帯に使用する。',
            '角を折り：南無大慈悲父！（3回）',
            '霊験お札の神霊、天人、護法神の降臨をお願いする！（3回）',
            '供物を並べる：赤いもの、香、花、果物、お茶、お菓子など、都合に合わせて供養する。門下の子孫はすべて供養できる。',
            '師匠、本命、護法の降臨を祈願する！（1回）',
            '霊験お札の神霊、天人、護法の加護を祈願する！（3回）',
            '自分が解決したい災難について説明し、加持と加護を求める。',
            '大明咒を21回以上唱え、霊験お札の神霊、天人、護法神に回向し、感謝の意を表す。',
            '祈りを花や香に変え、または紙を火で焼く。詳細はお札の巻物の指示文を参照。'
        ],
        footer: '霊験お札検索システム © 2025 | 吉を求め凶を避け、災いを消し福を招く',
        inputValidation: '旧暦生年月と時刻の情報をすべて入力してください！',
        inputSummary: '旧暦生：{birthYear}（{birthZodiac}年）{birthMonth}{birthTime} | 現在の年：{currentYear}（{currentYearZodiac}年）',
        yearFormat: '{year}（{zodiac}年）',
        languageName: '日本語'
    },
    'ko': { // 韩文
        title: '영험부적 검색 시스템',
        subtitle: '천기를 탐구하고, 운명을 분석하며, 재앙을 물리치고, 복을 부르며, 길함을 추구하고 흉함을 피하다',
        birthYear: '음력 출생년도',
        birthMonth: '음력 출생월',
        birthTime: '출생시간',
        pleaseSelect: '선택해주세요',
        month1: '정월',
        month2: '2월',
        month3: '3월',
        month4: '4월',
        month5: '5월',
        month6: '6월',
        month7: '7월',
        month8: '8월',
        month9: '9월',
        month10: '10월',
        month11: '11월',
        month12: '12월',
        hour1: '자시 (23:00-01:00)',
        hour2: '축시 (01:00-03:00)',
        hour3: '인시 (03:00-05:00)',
        hour4: '묘시 (05:00-07:00)',
        hour5: '진시 (07:00-09:00)',
        hour6: '사시 (09:00-11:00)',
        hour7: '오시 (11:00-13:00)',
        hour8: '미시 (13:00-15:00)',
        hour9: '신시 (15:00-17:00)',
        hour10: '유시 (17:00-19:00)',
        hour11: '술시 (19:00-21:00)',
        hour12: '해시 (21:00-23:00)',
        queryBtn: '부적 검색',
        resultTitle: '부적 명리 분석 결과',
        bengMing: '본명궁위',
        suiJun: '세군',
        fortune: '길흉',
        lingFu: '부적',
        effect: '효용',
        usageMethod: '부적 사용 방법',
        usageSteps: [
            '불당이나 깨끗한 장소에서 해가 뜬 후부터 정오 13:00 사이에 진행하며, 일부 부적은 다른 시간대에 사용한다.',
            '모서리를 접고: 나무대자비부! (3번)',
            '영험 부적의 신령, 천인, 호법신의 강림을 청한다! (3번)',
            '공물 배치: 붉은 것, 향, 꽃, 과일, 차, 과자 등을 편의에 따라 공양하며, 문하의 자손은 모두 공양할 수 있다.',
            '스승, 본명, 호법의 강림을 기원한다! (1번)',
            '영험 부적의 신령, 천인, 호법의 보호를 기원한다! (3번)',
            '자신이 해결하고자 하는 재난에 대해 설명하고, 가지와 보호를 요청한다.',
            '대명주를 21번 이상 외우고, 영험 부적의 신령, 천인, 호법신에게 회향하며 감사의 마음을 표한다.',
            '기도를 꽃이나 향으로 변화시키거나, 종이를 불에 태운다. 자세한 내용은 부적 두루마리의 지시문을 참조한다.'
        ],
        footer: '영험부적 검색 시스템 © 2025 | 길함을 추구하고 흉함을 피하며, 재앙을 물리치고 복을 부르다',
        inputValidation: '음력 출생년월과 시간 정보를 모두 입력해주세요!',
        inputSummary: '음력 출생: {birthYear}년({birthZodiac}년) {birthMonth} {birthTime}시 | 현재 년도: {currentYear}년({currentYearZodiac}년)',
        yearFormat: '{year}년 ({zodiac}년)',
        languageName: '한국어'
    }